# Advanced configuration file for BluginBuilder plugin
# Some of these settings are safe, others can break your server if modified incorrectly
# New settings/defaults won't appear automatically on this file when upgrading

#Pre-processing settings
preprocessing:
  #Split multiple class/trait/interface
  splitting: true

  #Renaming mode settings
  #Modes Supported : shorten, serial(Sequential variable), md5(5 character hash text),  false(disable)
  renaming:
    local-variable: serial
    private-property: serial
    private-method: serial
    private-const: serial

  #Import processing settings
  importing:
    #Import renaming  settings
    #Modes Supported : {ALL renaming mode}, resolve(Remove import statement), false(disable)
    #Selecting a resolve mode disables forcing, grouping, and sorting.
    renaming: serial

    #Whether to make import force
    forcing: true

    #Whether to make import grouping
    grouping: true

    #Whether to sort import
    sorting: true

  #Meaningless comment cleanup
  comment-optimizing: true

#Build settings
build:
  #Code output format setting
  #Modes Supported : standard(Default code style), shorten(Short code style)
  print-format: [standard]

  #Set whether to include only minimal files
  include-minimal: true

  #Whether to write Phar metadata
  skip-metadata: true

  #Whether to write Phar stub
  skip-stub: true